export const LOAD_GAME = 'LOAD_GAME';
export const MOVE_TO_LOCATION = 'MOVE_TO_LOCATION';
export const SELECT_COUNTER = 'SELECT_COUNTER';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SET_CURRENT_LOCATION_ID = 'SET_CURRENT_LOCATION_ID';